apiVersion: v1
kind: Service
metadata:
  name: ps-bff-service
  labels:
    backend: ps-bff
spec:
  selector:
    app: ps-bff
    type: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
status: {}