server:
  port: 8080

app:
  url: http://ps-app-frontend.rancher.local/

keycloak:
  realm: https://office.pergersoft.hu/auth/realms/pssecurity
  account: ${keycloak.realm}/account

api:
  resource1: http://ps-servlet-api.default.svc.cluster.local:8081kubectl/
  resource2: http://ps-reactive-api.default.svc.cluster.local:8082/

azure:
  tenant-id: ${AZURE_TENANT_ID}
  tenant-url: https://login.microsoftonline.com/${azure.tenant-id}

spring:
  security:
    oauth2:
      client:
        registration:
          PSSecurity:
            # https://medium.com/@bcarunmail/securing-rest-api-using-keycloak-and-spring-oauth2-6ddf3a1efcc2
            # https://developers.redhat.com/articles/2022/12/07/how-implement-single-sign-out-keycloak-spring-boot#keycloak_configuration
            client-id: ${OAUTH_CLIENT_ID}
            client-secret: ${OAUTH_CLIENT_SECRET}
            scope: openid, roles, email, profile
            authorization-grant-type: authorization_code
            redirect-uri: ${app.url}/login/oauth2/code/pssecurity
          MSLogin:
            # https://medium.com/@bcarunmail/securing-rest-api-using-keycloak-and-spring-oauth2-6ddf3a1efcc2
            # https://developers.redhat.com/articles/2022/12/07/how-implement-single-sign-out-keycloak-spring-boot#keycloak_configuration
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            scope: openid, email, profile, api://${AZURE_CLIENT_ID}/access_resources
            authorization-grant-type: authorization_code
            redirect-uri: ${app.url}/login/oauth2/code/azure
        provider:
          PSSecurity:
            authorization-uri: ${keycloak.realm}/protocol/openid-connect/auth
            token-uri: ${keycloak.realm}/protocol/openid-connect/token
            user-info-uri: ${keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${keycloak.realm}/protocol/openid-connect/certs
            user-name-attribute: preferred_username
          MSLogin:
            authorization-uri: ${azure.tenant-url}/oauth2/v2.0/authorize
            token-uri: ${azure.tenant-url}/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/oidc/userinfo
            jwk-set-uri: ${azure.tenant-url}/discovery/v2.0/keys
            user-name-attribute: name

  thymeleaf:
    cache: false


